### ISSUE TITLE
Nodes parsed differently when returned as an object?

### ISSUE THREAD

**Issue by horyd** [brikteknologier/seraph#147]
Hi guys,

I am not sure if this is an issue with seraph exactly, but figure you guys will know better than me ;)

What is happening is if I query a set of nodes normally like so:

MATCH n
RETURN collect(n)

Then the returned array from db.query has the node properties and it's ID. However if I attempt something like this:

MATCH n
RETURN collect({n: n})

Then the returned array contains entries with property "n" which contains all the node URI's, a "data" property containing the node's properties except it is missing the explicit ID property that is normally returned as above.

I'm lost as to where in the stack (Seraph, GrapheneDb, Neo4j) this difference is coming from. Any help is greatly appreciated.

Cheers

Jaryd

**Comment by HugoCornu** [comment]
Hi Jon,
When using collect(node.property), I too get results like
 {'0':valeur1,'1':valeur2}
when expecting
[valeur1,valeur2]

**Comment by jonpacker** [comment]
Looks like the above changes were never actually merged in. I'll take a look at it when I get time :)

**Comment by HugoCornu** [comment]
Thx!

**Comment by HugoCornu** [comment]
Hi Jon, I think I got it : 

<pre><code>function extractAttributes(item) {
  if (self._isNode(item)) {
    return self._createNodeObject(item);
  } else if (self._isRelationship(item)) {
    return self._createRelationshipObject(item);
  } else if (item === Object(item)) {
    var temp = {};
    Object.keys(item).forEach(function(key) {
      temp[key] = extractAttributes(item[key])
    })
    return temp;
  } else {
    return item;
  }
}</code></pre>

Doesn't work well when item is an Array. Because it handle the array like it would handle an object
Therefor I propose : 

<pre><code>function extractAttributes(item) {
  if (self._isNode(item)) {
    return self._createNodeObject(item);
  } else if (self._isRelationship(item)) {
    return self._createRelationshipObject(item);
 } else if (Array.isArray(item)) {
        var temp = [];
	item.forEach(function(subitem) {
            temp.push(extractAttributes(subitem))
        })
	return temp;  
} else if (item === Object(item)) {
    var temp = {};
    Object.keys(item).forEach(function(key) {
      temp[key] = extractAttributes(item[key])
    })
    return temp;
  } else {
    return item;
  }
}</code></pre>

**Comment by jonpacker** [comment]
Thanks for the help! I ended up going with this:

```javascript
function extractAttributes(item) {
          if (self._isNode(item)) {
            return self._createNodeObject(item);
          } else if (self._isRelationship(item)) {
            return self._createRelationshipObject(item);
          } else if (Array.isArray(item)) {
            return item.map(extractAttributes);
          } else if (item === Object(item)) {
            return _.mapObject(item, extractAttributes);
          } else {
            return item;
          }
        }
```

**Comment by HugoCornu** [comment]
Glad to have helped! Thx for Seraph
