### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by MichaelJCole** [brikteknologier/seraph#149]
Hey, sorry if I made too many issues re: this, but it seemed important.

seraph, seraph-model, seraph-resource tests are all failing because disposable-seraph isn't initializing correctly - I think it's having trouble downloading the database server.

See also:

https://github.com/brikteknologier/disposable-seraph/issues/7
https://github.com/brikteknologier/seraph-resource/issues/37

Looks like a cool project.  Want to use!

Thanks!

Mike

**Comment by jonpacker** [comment]
Hey! Sorry that I never replied to this, but I did fix the problem a little while back. iirc it was because neo changed their download link, and disposable-seraph couldn't find the file to download.

**Comment by MichaelJCole** [comment]
Cool, thanks!
