### ISSUE TITLE
Support for Neo4j auth plugin

### ISSUE THREAD

**Issue by cesarBere** [brikteknologier/seraph#156]
Hi,

We're using the [Neo4j auth plugin](https://github.com/neo4j-contrib/authentication-extension), do you plan to support it anytime soon ? 

Thanks !

**Comment by jonpacker** [comment]
No concrete plans, but I'll leave this issue open and that can serve as a reminder to look into it. Thanks.

**Comment by krnlde** [comment]
It looks like neo4j made the auth obligatory. Downloading the latest 2.2 server I had to setup a username:password combo. Since then seraph can't pull or put any data, obviously. The docs don't provide some authorization process.

Suggestions?

**Comment by jonpacker** [comment]
Hi! As of seraph 0.11.0 we support Neo4j's basic authentication (currently the only method they provide). They say more is coming in neo4j 2.3 as well, so in any case I won't be looking at supporting a third party plugin now that there is official support being added.

**Comment by krnlde** [comment]
Nice man! Thank you :)

**Comment by cesarBere** [comment]
Perfect ! Thanks :)
