### ISSUE TITLE
db.query does not always return array

### ISSUE THREAD

**Issue by HugoCornu** [brikteknologier/seraph#157]
Hi,

I have observed the following behavior : 
When using db.query, if the Cypher return 1 single element, the callback of db.query doesnt return an array.
When using db.query, if the Cypher return several elements, the callback of db.query return  an array.

Am I right?
Or am I missing an option that force the result to be array.

It is probably "by desgin" but I though the doc should reflect this!
Or the result could always be an array even if its an array of 1 element!

**Comment by jonpacker** [comment]
That's right. The docs should better show that. Ideally I'd actually like to make it consistent so that it's always an array, but it's a breaking change for people already consuming the API as it is. I'll keep this issue open as an issue to fix the docs.

**Comment by HugoCornu** [comment]
Thanks,

In my project, i lazily made it consistent by adding a function "db.queryArray" which basically runs db.query and put the result in an array when needed. This way I don't break any of the modules I use on top of Seraph.

I also wanted to grab the opportunity to say how great your work is. I really look up to people who like yourself take time to produce and maintain open tools for the community.
You ARE a hero in my honest opinion.

**Comment by sometimesalready** [comment]
Hello, @HugoCornu!
Can you please explain how you inspect result to be single object vs array

**Comment by jonpacker** [comment]
This is a pretty good way:

db.query("", function(err, result) {
  if (Array.isArray(result) {
    //it's an array
  } else {
    //it's one object
  }
});

**Comment by sometimesalready** [comment]
thank you, @jonpacker, a lot!
it is working.
