### ISSUE TITLE
underscore being overwritten

### ISSUE THREAD

**Issue by Cydt** [brikteknologier/seraph#158]
I've come across a pretty weird error when using seraph. In the file seraph.js, the line `} catch (_) {}` (line 149 currently) overwrites the underscore library variable under some circumstances. When I replace the underscore with any other variable everything works again.

**Comment by jonpacker** [comment]
Dude. That is mega weird! We'll definitely change it. Could you suggest a test that triggers it so that we can write a unit test for it (or if you feel like it, feel free to make a PR yourself!).

Nice catch! (pun unintended)
