### ISSUE TITLE
Neo4j 2.2 token for cypher queries

### ISSUE THREAD

**Issue by danieleguido** [brikteknologier/seraph#159]
Hi !
first of all thanks a lot for this library.
I has some troubles in migrating to neo4j 2.2 since it implements tokens.
Could be possible to implement it into seraph?

Thanks 
Daniele

**Comment by jonpacker** [comment]
Hi! This is now supported as of seraph 0.11.0. Please see the new [server options docs](https://github.com/brikteknologier/seraph#seraphserveroptions) to see how to specify your username/password when initialising seraph.

**Comment by jonpacker** [comment]
Also I'm assuming you're talking about auth tokens here. Please correct me if I'm wrong :)

**Comment by danieleguido** [comment]
Yep, exactly, thanks!
