### ISSUE TITLE
Server Authentication

### ISSUE THREAD

**Issue by georgelaughalot** [brikteknologier/seraph#160]
In some cases its nice to be able to do basic server authentication, and with newer versions of Neo4j its built in. That being said, it can be added with something as simple as 

```
  var requestOpts = {
    uri: this.options.server + this.options.endpoint + '/' + operation.to,
    method: operation.method,
    headers: {
      'Accept': 'application/json',
    }
  };

  if (this.options.user && this.options.pass)
    requestOpts.headers.Authorization = 'Basic ' + new Buffer( this.options.user + ":" + this.options.pass ).toString('base64');
```

Simply adding the if statement after the declaration of `requestOpts` solves the problem for me, however i hate altering these things, as i have to go alter them in every environment. Any chance you could role this, or something similar into the module?

**Comment by chrishiestand** [comment]
+1

**Comment by sim-san** [comment]
+1

**Comment by jonpacker** [comment]
Hey! I've added support for this now. You can specify a `user` and `pass` in the server options, and change the password of the server using `db.changePassword(newPass, cb)`. Docs for the new options here https://github.com/brikteknologier/seraph#seraphserveroptions
