### ISSUE TITLE
simple insert not working on GrapheneDB 

### ISSUE THREAD

**Issue by pranavpunjabi** [brikteknologier/seraph#161]
I have a remote db hosted on GrapheneDB. I am trying to insert a node into my db.

```javascript
var db = require("seraph")({ server: "http://ompdb.sb05.stations.graphenedb.com:24789",
	user: "user",
	pass: "password" });


// var db = require("seraph")({ server: "http://user:password@ompdb.sb05.stations.graphenedb.com:24789"});

db.save({ name: "Test-Man", age: 40 }, function(err, node) {
	if (err) 
		throw err;
	else 
		console.log("Inserted");
});
```

 I receive a 500 error when trying to insert this node. 

Am I properly using the Seraph driver?

**Comment by deestan** [comment]
I think the problem is unrelated to Seraph. When I try to browse http://ompdb.sb05.stations.graphenedb.com:24789/browser/ , and log in with the given credentials, neo4j's web interface gives me a 500.
