### ISSUE TITLE
Nested results of collect are Objects, not Array?

### ISSUE THREAD

**Issue by rdkls** [brikteknologier/seraph#164]
Hello fellow graphers
Say I have 2 node types, Product and Image
Product can have multiple Images
I want to get a list of Products, each having a property (sub-element) containing all of its Images
If the data structure is like so:
```
MERGE (p:Product {name: "Raygun"})
MERGE (p)-[:HAS_IMAGE]-(i:Image {url: "http://image1.com"})
MERGE (p)-[:HAS_IMAGE]-(i2:Image {url: "http://image2.com"})
```
My cypher is like
```
MATCH (p:Product )
OPTIONAL MATCH (p)-[]->(i:Image)
RETURN ({
name: p.name, images: COLLECT(i)
}) as product
```
The results from Neo4j REST API have "images" as an array, as might be expected (this is exactly what I want) e.g.
```
{ name: 'Raygun',
images: [
  {url: 'http://image1.com'},
  {url: 'http://image2.com'}
]
```
However, the results from Seraph have "images" as a dict keyed on index, like
```
{ name: 'Raygun',
images: {
  "0": {url: 'http://image1.com'},
  "1": {url: 'http://image2.com'}
}

```

**Comment by jonpacker** [comment]
Which version of Seraph are you using?

**Comment by rdkls** [comment]
Sorry - 0.11.2

**Comment by jonpacker** [comment]
Could you try updating to 0.11.3 and trying again?

**Comment by rdkls** [comment]
It worked! Thanks Jon

**Comment by jonpacker** [comment]
No worries, it was only just fixed :)
