### ISSUE TITLE
unable to update with label

### ISSUE THREAD

**Issue by shinymayhem** [brikteknologier/seraph#165]
When attempting to update a node using `save(node, label, callback)`, I'm getting an error, `Illegal character in path at index 2: ./{0}/labels`. I'm not sure how the referencing a previous node in a transaction is supposed to work, but here is the `operations` array from the seraph node's `save` function at the time of the error:
```javascript
  operations:
   [ { method: 'PUT',
       endpoint: '/db/data',
       to: 'node/4/properties',
       body: [Object],
       id: 0 },
     { method: 'POST',
       endpoint: '/db/data',
       to: '{0}/labels',
       body: 'Default',
       id: 1 } ]
```
where the first operation's `body` is like
```javascript
 { name: 'updatedNode', key: 'value', type: 'default' }
```
and the input node to the `save` function is like 
```javascript
{ name: 'updatedNode', key: 'value', type: 'default', id: 4 }
```

**Comment by jonpacker** [comment]
That's correct. It's a limitation of the batching API implementation that you cannot save a node with a inside a batch. This is documented in the [node.save](https://github.com/brikteknologier/seraph#node.save) documentation.

**Comment by jonpacker** [comment]
The reason is that ordinarily, `node.save` uses a batch internally to assure the node is saved atomically with the label, or not saved at all. Since batches cannot be nested, it doesn't work inside another batch.

But! Since you're already in a batch, atomicity is assured anyway. So you can do this:

```javascript
var txn = db.batch();
var node = txn.save({name: 'my node'});
txn.label(node, 'my_label');
txn.commit();
```

**Comment by shinymayhem** [comment]
I understood that I can't save with labels within a batch, but I'm not doing anything with batches in my code. I'm just doing a `db.save(node, label, callback)` all by itself. The batch stuff that I'm talking about is what you referred to as batching internally. 

If I'm still misunderstanding, then the documentation should make it clear that `save` can only have the label argument for new nodes.

**Comment by jonpacker** [comment]
Ah! My mistake, I totally misunderstood :). Ideally it should be able to handle this. I'll see if I can fix it.
