### ISSUE TITLE
what are db.query results?

### ISSUE THREAD

**Issue by one2gov** [brikteknologier/seraph#166]
This is console.log(result); 

`{ columns: [ 'n.name' ],
  data: [ [ '(' ], [ 'node_name' ], [ ';' ], [ 'CREATE' ], [ ')' ] ] }`

of `MATCH (n)-[r:CREATE_NODE_COMMAND]->(s)RETURN n.name`

How do i turn it in the `(node_name;CREATE)` ?
Is this array of objects or dict or jsonArray?

The best result i get so far is `JSON.stringify(result[key])`
and it's `[["("],["node_name"],[";"],["CREATE"],[")"]]`

**Comment by jonpacker** [comment]
I'm sorry, I don't understand, can you provide a little more context? Those appear to be the results of a raw query, are you using `queryRaw`? Can you post an entire code snippet, including the query? And your expected result?

**Comment by one2gov** [comment]
**Server code**
io.sockets.on('connection', function(socket){
function show() {
    var cypher = [
     'MATCH (n)-[r:CREATE_NODE_COMMAND]->(s)RETURN n.name'
     ].join('\n');
        db.queryRaw(cypher, {}, function(err, result) {
  if (err) throw err;
      console.log(result);
      socket.emit('showres', {'showres': JSON.stringify(result[key])});


**Frontend**
 onclick="socket.emit('show');"

**Result**
{ columns: [ 'n.name' ],
  data: [ [ '(' ], [ 'node_name' ], [ ';' ], [ 'CREATE' ], [ ')' ] ] }
 
I am trying to get data values which is
(node_name;CREATE)

But i can't get rid of braces and parenthesis because i don't understand what kind of objects are results.

I am sorry for not being clear, i am a beginner and there is a lot of specific vocabulary.

**Comment by jonpacker** [comment]
`result.data.join('')`

**Comment by one2gov** [comment]
Thank you Jon)
