### ISSUE TITLE
Can you cancel/rollback a batch?

### ISSUE THREAD

**Issue by tommymessbauer** [brikteknologier/seraph#172]
Is it possible to cancel/rollback a batch once it has been started?

```
var txn = db.batch();
txn.save({ dogs: true });

// something happens that makes this transaction no longer needed (especially in the async form)

txn.cancel();
```

**Comment by jonpacker** [comment]
Seraph's `batch` function uses the Batch API, which doesn't send anything to the server until you call "commit". There's no need to rollback a batch before you commit, because nothing has actually been sent to the server yet.
