### ISSUE TITLE
optional match not returning results

### ISSUE THREAD

**Issue by beebase** [brikteknologier/seraph#179]
This is what I get using neo4j webbrowser:
![image](https://cloud.githubusercontent.com/assets/446089/9977256/02b2645e-5f01-11e5-976b-a36c349129ba.png)

This is what I get using seraph:
![image](https://cloud.githubusercontent.com/assets/446089/9977265/5577fde8-5f01-11e5-999e-aef447c9da87.png)

![image](https://cloud.githubusercontent.com/assets/446089/9977258/35bbde3e-5f01-11e5-8198-3b9366dd1696.png)

Shouldn't this work?

**Comment by beebase** [comment]
This doesn't seem related to seraph. It's not working, even when I use plain neo4j rest-api or other npm modules like neo4j-node.
I added a post here: 
http://stackoverflow.com/questions/32678074/optional-match-not-returning-result

**Comment by jonpacker** [comment]
Just out of interest, have you tried `{recId: parseInt(recId)}`? It's possible that the REST API isn't very forgiving with types in that comparison there.

**Comment by beebase** [comment]
Yes! That's it. Thanks, I was going nuts here. 
If you're on stackoverflow, you might want to answer my post, so I can mark it as a correct answer.

**Comment by jonpacker** [comment]
I'll do that :) glad I could help.
