### ISSUE TITLE
If any property named id, it cannot be retrieved, but _id is retrieved instead

### ISSUE THREAD

**Issue by toniher** [brikteknologier/seraph#180]
Hello,
in case a node has a property named id (different from _id, internal Neo4j ID), this is not retrieved but internal ID instead.

**Comment by spencerkohan** [comment]
I'm running into this also

**Comment by jonpacker** [comment]
You need to define your own ID property when instantiating seraph, like this:

```javascript
var db = seraph({
  server: 'http://localhost:7474',
  id: 'internal_id'
});
```

Now, neo4j's internal ID's will be stored on the `internal_id` property, and `id` will be free.

**Comment by jonpacker** [comment]
If this is what you're trying and it's not working, please reopen and let me know :)
