### ISSUE TITLE
Test connection parameters

### ISSUE THREAD

**Issue by ssimono** [brikteknologier/seraph#183]
The connection parameters (user, password, etc) are currently set in constructor and then directly used in each request.

The problem for me is that I cannot be sure that credentials are correct and neo4j server is reachable until a first "real" query is made, crashing my application at a random point instead of cleanly noticing that neo4j connection is wrong.

I could obviously start by doing a useless query to do so, but what would you think about a kind of `testConnection` method that could return an error?

One way to do so would be to query the [api service root](http://neo4j.com/docs/2.2.5/rest-api-service-root.html) which returns generic information and is still required to be authenticated.

**Comment by jonpacker** [comment]
That's a good idea. I'll try and get it in there. In the meantime you could just do a completely useless query like `RETURN timestamp()` that doesn't touch any data. That's probably how any `testConnection` method will work.
