### ISSUE TITLE
Volatile IDs used, any chance having next versions to support persistent UUIDs?

### ISSUE THREAD

**Issue by alex-alfaro** [brikteknologier/seraph#184]
As per Neo4j Manual:

"Neo4j reuses its internal ids when nodes and relationships are deleted. This means that applications using, and relying on internal Neo4j ids, are brittle or at risk of making mistakes. Rather use application generated ids."

So it would be convenient/mandatory for Production grade apps that seraph supports Application generated ids instead of node's internal id. Are there any plans to change this?

**Comment by jonpacker** [comment]
Please see the discussion here https://github.com/brikteknologier/seraph/issues/162
