### ISSUE TITLE
Can't create node with a label in a single call

### ISSUE THREAD

**Issue by swist** [brikteknologier/seraph#185]
I am trying to create a company with a label in a single `db.save` call, but I get `neo4jError:NullPointerException`

my code is:

```
db.save({name: "test"}, "Company", function(err, node){
	console.log(err, node);
});	
```

When I use a `db.label` in the callback it works:

```
db.save({name: "test"}, function(err, node){
	db.label(node, "Company", function(err, node){
		console.log(err, node);
	});
});	
```

Is this the expected behaviour? The documentation suggests that the first option should be possible.

**Comment by jonpacker** [comment]
I can't seem to replicate. Which version of neo4j are you using? Here's what happens for me:

```
 var s = require('./lib/seraph')
undefined
> var db = s()
undefined
> db.save({name:'Test'}, 'Company', function(err, node) { console.log(err, node) })
undefined
> null { name: 'Test', id: 4567 }
```

**Comment by jonpacker** [comment]
Please reopen if you have some steps to replicate!
