### ISSUE TITLE
Isomorphic/universal use of seraph

### ISSUE THREAD

**Issue by ArnoBuschmann** [brikteknologier/seraph#187]
Hello,

when I try to use Seraph isomorphically/universally, Webpack wants it to have a loader.

The errors are looking like this:

```javascript
ERROR in ./~/seraph/~/request/~/har-validator/lib/schemas/cacheEntry.json
Module parse failed: /home/arno/Dokumente/arno/tylor-cycle-starter/cycle-starter/node_modules/seraph/node_modules/request/node_modules/har-validator/lib/schemas/cacheEntry.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "oneOf": [{
|     "type": "object",
|     "optional": true,
 @ ./~/seraph/~/request/~/har-validator/lib/schemas/index.js 5:14-42
```

Has anyone a way/suggestion, how I can fix it?

**Comment by jonpacker** [comment]
I've never used webpack. It looks like it's having a problem with the latest version of the `request` module. It is possible that this will fix itself if the `request` module releases a patch.
