### ISSUE TITLE
Test case suite fails on Neo4j v 2.3

### ISSUE THREAD

**Issue by corporatepiyush** [brikteknologier/seraph#188]
i am getting following error on Neo4j 2.3 and Node 4.2.2

> ./node_modules/mocha/bin/mocha -R spec -t 10000 -s 2000

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

  1) "before all" hook

  ✖ 1 of 144 tests failed:

  1)  "before all" hook:
     Error: Starting Neo4j Server...WARNING: not changing user
process [7109]... waiting for server to be ready.. Failed to start within 120 seconds.
Neo4j Server may have failed to start, please check the logs.

      at ChildProcess.<anonymous> (/Users/redpanda/work/github/seraph/node_modules/disposable-seraph/node_modules/neo4j-supervisor/neosv.js:46:24)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

npm ERR! Test failed.  See above for more details.

**Comment by jonpacker** [comment]
This happens sometimes when neo4j fails to shut down properly or tries to migrate an older datastore that has not been properly deinitialized. I am not really sure why it happens, but you should be able to fix it by purging your `node_modules` and `npm install`ing again, then doing a long running `mocha -R spec -t 300000` to download/install neo4j again.
