### ISSUE TITLE
find with label returns nodes that don't have that label

### ISSUE THREAD

**Issue by baltar** [brikteknologier/seraph#189]
Executing this on my db (where variable s is my seraph instance):

```javascript
s.find({sqlId: 215}, true, 'client', function(error, nodes) {
  _.map(nodes, function(node) {s.readLabels(node, console.log)});
});
```
outputs this:
```javascript
[ 'client', 'person' ]
[ 'person', 'driver' ]
```

If I understand the documentation for find correctly, the "any" parameter should only affect the predicate object, but not the label constraint, so only the first node with labels [ 'client', 'person' ] should be returned in my example.

**Comment by jonpacker** [comment]
You're right, that is definitely some super strange behaviour. I don't really know why that would happen. Could you possibly insert a `console.log(cypher)` at line 313 in `node_modules/seraph/lib/node.js`, run the `find` again, and copy and paste the cypher query in here?

**Comment by jonpacker** [comment]
Can't replicate. Will open again if more information is provided.

**Comment by baltar** [comment]
This was actually because of a neo4j bug corrupting the cache during an upgrade, see https://github.com/neo4j/neo4j/issues/5991

After I deleted the schema and index folders as described there, seraph.readLabels also worked again as expected. 

Sorry I forgot to close this issue.
