### ISSUE TITLE
I want to provide my own object id while creating object

### ISSUE THREAD

**Issue by rohandalvi** [brikteknologier/seraph#190]
If I provide id on db.save({id: 'someid' , name: object.name});

It returns error saying id doesn't exist. Well, I am trying to create a new object with id value of my choice. Isn't there any way to achieve this?

**Comment by jonpacker** [comment]
You need to move the internal `id` to a different property. You can do that by changing the `id` option when initializing seraph:

```javascript
var db = seraph({
  id: 'internal_id',
  server: 'http://localhost:7474'
});
```

Now the internal id will be stored the the `internal_id` property and the `id` property will be free to use for your own purposes.
