### ISSUE TITLE
Support saving multiple labels – db.save( {properties}, [labelA, labelB] )

### ISSUE THREAD

**Issue by n321203** [brikteknologier/seraph#192]
Feature request: Allow an array of labels to be passed to db.save():

```
db.save({title: 'Seraph', data:123}, ['Library', 'Cool', 'Todo'], function(err, node) {

})
```

**Comment by jonpacker** [comment]
This should absolutely work. I've added a test for it here f48eda2 - and it's passing for me. Open again if you're having troubles with it.
