### ISSUE TITLE
No error specified in COMMIT callback when batching

### ISSUE THREAD

**Issue by sometimesalready** [brikteknologier/seraph#193]
I do not specify callbacks to all queries in transaction cause it is possible to get aggregated result in commit callback. But as follow from code snippet it is not true for errors. Should errors be aggregated as well as results in commit callback?
```javascript
db.batch(function(txn) {
    txn.query('MATCH n RETUUURN n', error => console.log(error)); // {code, message}
}, error => console.log(error)); // null
```

**Comment by jonpacker** [comment]
Awesome! Thanks! Sorry it took so long to get to it, I've been on vacation for a few weeks.
