### ISSUE TITLE
Node deletion error - 'Parentheses are required to identify nodes in pattern'

### ISSUE THREAD

**Issue by brasskazoo** [brikteknologier/seraph#199]
Deleting a node with the delete(id, force=true, ..) function results in this error:

    { code: 'Neo.ClientError.Statement.SyntaxError',
      message: 'Parentheses are required to identify nodes in patterns, i.e. (node) (line 1, column 40 (offset: 39))
    "START node=node({root}) OPTIONAL MATCH node-[rel]-() DELETE node, rel"
                                            ^' }

This message seems to indicate that `node-[rel]-()` should be `(node)-[rel]-()` in node.js:198

Using neo4j 3.0.1 community and Seraph 0.14.3.

**Comment by jonpacker** [comment]
Thanks! Haven't quite had the time to sit down and make everything neo4j 3 compatible yet, so if you find any other problems don't hesitate to post them here.

**Comment by brasskazoo** [comment]
No problem :)
