### ISSUE TITLE
Create DataBase Neo4j with node js

### ISSUE THREAD

**Issue by rezguiHamza** [brikteknologier/seraph#200]
i have a problem to create a db neoj, this my code in my file server.js:

var db = require("seraph")({
server: "http://127.0.0.1:7474",
endpoint: "data/graph.db",
user: "neo4j",
pass: "neo4j"
})
, graph = require("neo4jquery").setConnection(db)

, query = "CREATE (vous:Personne { nom:'Vous' })RETURN vous" ;

graph.Query(query, false, function(err, list) {
if (err) {
// callback(err, void 0);
console.log("ERROR Execution" + err);
} else {
// some stuff here with list

console.log("requete executée !");
    var user = list[0];
  }
});
if i connect in http://127.0.0.1:7474 : " Invalid username or password."

when i run server.js it shows me : "ERROR ExecutionError: Invalid username or password."

although I added these two line in "neo4j-server.properties" :

org.neo4j.server.credentials=neo4j:neo4j org.neo4j.server.thirdparty_jaxrs_classes=org.neo4j.server.extension.auth=/auth

**Comment by jonpacker** [comment]
`org.neo4j.server.credentials=neo4:neo4j` is different to `user: "neo4j", pass: "neo4j"`, could that be your problem? try `user: "neo4", pass: "neo4j"`

**Comment by rezguiHamza** [comment]
hi @jonpacker,

I was wrong!
